subprojects {
	apply plugin: "java-library"
	
	repositories {
        maven {
			name = "sponge"
			url = "https://repo.spongepowered.org/repository/maven-public/"
		}
		maven {
			name = "sonatype-oss-snapshots1"
			url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
		}
		mavenLocal()
    }

	version = project.plugin_version
	group = project.plugin_group
	java.toolchain.languageVersion = JavaLanguageVersion.of(project.java_version)
	
	compileJava.options.encoding = "UTF-8"
}

[sub_api, sub_common, sub_vanilla, sub_forge, sub_neoforge].each {
	project(":$it").jar.destinationDirectory = file("$rootDir/artifacts")
}

project(":$sub_api") {
	dependencies {
		// SpongeAPI
		api "org.spongepowered:spongeapi:${spongeapi_version}"
		
		// DataFixerUpper
		api "com.mojang:datafixerupper:${lib_version_dfu}"
	}
	
	base.archivesName = project.plugin_name + "-api"
}

project(":$sub_common") {
	//apply plugin: 'com.gradleup.shadow'
	//apply plugin: 'org.spongepowered.gradle.plugin'
	//apply plugin: 'org.spongepowered.gradle.vanilla'
	
	dependencies {
		// SpongeToolsAPI
		implementation project(":$sub_api")
		
		// SpongeCommon
		api "org.spongepowered:sponge:${sponge_version}"
		
		// Mixins
		api "org.spongepowered:mixin:${lib_version_mixin}"
		api "io.github.llamalad7:mixinextras-common:${lib_version_mixinextras}"
		
		// Dynamic class creation
		api "net.bytebuddy:byte-buddy:${lib_version_bytebuddy}"
	}
	
	jar {
		from project(":$sub_api").sourceSets.main.output
		
		manifest {
			attributes "MixinConfigs": "mixins.spongetools.json"
		}
	}
	
	base.archivesName = project.plugin_name + "-common"
}

project(":$sub_vanilla") {
	dependencies {
		api project(":$sub_common")
	}
	
	jar {
		from project(":$sub_api").sourceSets.main.output
		from project(":$sub_common").sourceSets.main.output
		
		manifest {
			attributes "MixinConfigs": "mixins.spongetools.json"
		}
	}
	
	base.archivesName = project.plugin_name + "-vanilla"
}

project(":$sub_forge") {
	dependencies {
		api project(":$sub_common")
	}
	
	jar {
		from project(":$sub_api").sourceSets.main.output
		from project(":$sub_common").sourceSets.main.output
		
		manifest {
			attributes "MixinConfigs": "mixins.spongetools.json"
		}
	}
	
	base.archivesName = project.plugin_name + "-forge"
}

project(":$sub_neoforge") {
	dependencies {
		api project(":$sub_common")
	}
	
	jar {
		from project(":$sub_api").sourceSets.main.output
		from project(":$sub_common").sourceSets.main.output
		
		manifest {
			attributes "MixinConfigs": "mixins.spongetools.json"
		}
	}
	
	base.archivesName = project.plugin_name + "-neoforge"
}
