plugins {
	id 'java-library'
}

compileJava.options.encoding = 'UTF-8'
targetCompatibility = 21
sourceCompatibility = 21

group = 'net.hellheim'
version = '0.3-SNAPSHOT'
description = 'SpongeToolsAPI'

repositories {
	jcenter()
	maven {
		name = 'sponge'
		url = 'https://repo.spongepowered.org/repository/maven-public/'
	}
	maven {
		name = "sonatype-oss-snapshots1"
		url = "https://s01.oss.sonatype.org/content/repositories/snapshots/"
	}
	
	mavenLocal()
}

dependencies {
	// SpongeAPI
	api 'org.spongepowered:spongeapi:14.0.0-SNAPSHOT'
	
	// DataFixerUpper
	api 'com.mojang:datafixerupper:8.0.16'
	
	// icu4j (for TimeZone in ItemModel)
	api 'com.ibm.icu:icu4j:76.1'
}

jar {
	archiveBaseName = "SpongeToolsAPI"
}
