
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
java_version = 21

spongeapi_version = 14.1.0-SNAPSHOT
sponge_version    = 1.21.4-14.0.0-SNAPSHOT
game_version      = 1.21.4

plugin_group   = net.hellheim
plugin_version = 0.3-SNAPSHOT

# Subprojects
plugin_name  = SpongeTools
sub_api      = SpongeToolsAPI
sub_common   = SpongeToolsCommon
sub_vanilla  = SpongeToolsVanilla
sub_forge    = SpongeToolsForge
sub_neoforge = SpongeToolsNeoforge
