
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
java_version = 25

spongeapi_version = 19.0.0-SNAPSHOT
sponge_version    = 26.1-19.0.0-SNAPSHOT
game_version      = 26.1

lib_version_dfu         = 8.0.16
lib_version_mixin       = 0.8.7
lib_version_mixinextras = 0.5.3
lib_version_bytebuddy   = 1.14.3

plugin_group   = net.hellheim
plugin_version = 0.4-SNAPSHOT

# Subprojects
plugin_name  = SpongeTools
sub_api      = SpongeToolsAPI
sub_common   = SpongeToolsCommon
sub_vanilla  = SpongeToolsVanilla
sub_forge    = SpongeToolsForge
sub_neoforge = SpongeToolsNeoforge
