plugins {
	id 'com.gradleup.shadow'
	id 'org.spongepowered.gradle.plugin'
	id 'org.spongepowered.gradle.vanilla'
}


sponge {
	apiVersion(project(":").spongeapi_version)
	license("MIT")
	loader {
		name("java_plain")
		version("1.0")
	}
	plugin("spongetools") {
		displayName(project(":").plugin_name)
		version(project(":").plugin_version)
		entrypoint("net.hellheim.spongetools.common.SpongeToolsPlugin")
		description("SpongeTools plugin")
		dependency("spongeapi") {
			//loadOrder(PluginDependency.LoadOrder.AFTER)
			optional(false)
		}
	}
}

minecraft {
	version(project.game_version)
}
